refactor

diff --git a/bin/mkapp b/bin/mkapp
--- a/bin/mkapp
+++ b/bin/mkapp
@@ -1,9 +1,95 @@
+#!/usr/bin/env bash
 #
-# mkapp exe
+# mkapp - scaffold up a new app for bitnami
 #
 
-dir="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"/..
+mkapp() {
+  
+  # settings
+  STACK="/opt/bitnami"
+  
+  # dep
+  source argue.sh || return 1
+  
+  # options
+  args=("$@")
+  argue "-d, --delete" || return 1
+  
+  # vars
+  app="${args[0]}"
+  names=("${args[@]}")
+  home="$STACK"/apps/"$app"
+  
+  # sanity
+  [ -z "$app" ] && echo "please specify an app name" >&2 && return 1
+  
+  if [ -z "${opts[0]}" ]
+  then
+    
+    # sanity
+    [ -d "$home" ] && echo "cannot create $app: app exists" >&2 && return 1
+  
+    # create stuff
+    mkapp_create_dirs || return 1
+    mkapp_create_vhosts || return 1
+    mkapp_link_vhosts || return 1
+    mkapp_chown_app || return 1
+    mkapp_reload_apache || return 1
+  else
+    
+    # delete stuff
+    mkapp_delete_app
+    mkapp_unlink_vhosts
+    mkapp_reload_apache || return 1
+  fi
+}
 
-source "$dir"/lib/mkapp.sh
+mkapp_create_dirs() {
+  sudo mkdir -p "$home"/conf
+  sudo mkdir -p "$home"/htdocs
+}
 
+mkapp_create_vhosts() {
+  for name in "${names[@]}"
+  do
+    echo "<VirtualHost *:*>
+  DocumentRoot $home/htdocs
+  ServerName $name
+  <Directory $home/htdocs>
+    Options +FollowSymLinks
+    AllowOverride All
+    <IfVersion < 2.3 >
+      Order allow,deny
+      Allow from all
+    </IfVersion>
+    <IfVersion >= 2.3>
+      Require all granted
+    </IfVersion>
+  </Directory>
+</VirtualHost>" | sudo tee -a "$home"/conf/httpd.conf > /dev/null
+  done
+}
+
+mkapp_link_vhosts() {
+  echo -e "Include \"$home/conf/httpd.conf\"" | sudo tee -a "$STACK"/apache2/conf/httpd.conf > /dev/null
+}
+
+mkapp_unlink_vhosts() {
+  line="$(cat "$STACK"/apache2/conf/httpd.conf | grep -n "Include \"$home/conf/httpd.conf\"" | sed "s/\(.*\):Include.*/\1/")"
+  [ -n "$line" ] && sed -i "${line}d;" "$STACK"/apache2/conf/httpd.conf
+}
+
+mkapp_chown_app() {
+  sudo chown -R bitnami:bitnami "$home"
+}
+
+mkapp_delete_app() {
+  sudo rm -rf "$home"
+}
+
+mkapp_reload_apache() {
+  sudo "$STACK"/ctlscript.sh restart apache
+}
+
+# run
 mkapp "$@"
